// Code generated by Kitex v0.4.4. DO NOT EDIT.

package userservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	userservice "mini-min-tiktok/kitex_gen/userservice"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Register(ctx context.Context, req *userservice.UserRegisterReq, callOptions ...callopt.Option) (r *userservice.UserRegisterResp, err error)
	Login(ctx context.Context, req *userservice.UserLoginReq, callOptions ...callopt.Option) (r *userservice.UserLoginResp, err error)
	FollowerList(ctx context.Context, req *userservice.RelationFollowerListReq, callOptions ...callopt.Option) (r *userservice.RelationFollowerListResp, err error)
	FriendList(ctx context.Context, req *userservice.RelationFriendListReq, callOptions ...callopt.Option) (r *userservice.RelationFriendListResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserserviceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserserviceClient struct {
	*kClient
}

func (p *kUserserviceClient) Register(ctx context.Context, req *userservice.UserRegisterReq, callOptions ...callopt.Option) (r *userservice.UserRegisterResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, req)
}

func (p *kUserserviceClient) Login(ctx context.Context, req *userservice.UserLoginReq, callOptions ...callopt.Option) (r *userservice.UserLoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, req)
}

func (p *kUserserviceClient) FollowerList(ctx context.Context, req *userservice.RelationFollowerListReq, callOptions ...callopt.Option) (r *userservice.RelationFollowerListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowerList(ctx, req)
}

func (p *kUserserviceClient) FriendList(ctx context.Context, req *userservice.RelationFriendListReq, callOptions ...callopt.Option) (r *userservice.RelationFriendListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FriendList(ctx, req)
}
