server:
	kitex -module mini-min-tiktok idl/video.thrift # execute in the project root directory
	kitex -module mini-min-tiktok -service videoservice -use mini-min-tiktok/kitex_gen -I=../../idl/ video.thrift # execute in cmd/video
