server:
	kitex -module mini-min-tiktok idl/user.thrift # execute in the project root directory
	kitex -module mini-min-tiktok -service userservice -use mini-min-tiktok/kitex_gen -I=../../idl/ user.thrift # execute in cmd/user
